### PR TITLE
Reduce misalignment within multi-line statements

### LINKED ISSUE #11: Misalignment with multiple line statements
> But if you do it as separate code-display (`print(io, src); lines = readlines(io)`) then one risks having the two get misaligned, whereas this version ensures that the two will always stay aligned.
> 
> Demo:
> ```julia
> julia> function buildexpr()
>            items = [7, 3]
>            ex = quote
>                X = $items
>                for x in X
>                    println(x)
>                end
>            end
>            return ex
>        end
> buildexpr (generic function with 1 method)
> 
> julia> @code_typed buildexpr()
> CodeInfo(
> 1 ─ %1  = Core.tuple(7, 3)::Core.Const((7, 3), false)
> │   %2  = $(Expr(:foreigncall, :(:jl_alloc_array_1d), Vector{Int64}, svec(Any, Int64), 0, :(:ccall), Vector{Int64}, 2, 2))::Vector{Int64}
> │         Base.arraysize(%2, 1)::Int64
> └──       goto #7 if not true
> 2 ┄ %5  = φ (#1 => 1, #6 => %10)::Int64
> │   %6  = φ (#1 => 1, #6 => %16)::Int64
> │   %7  = φ (#1 => 1, #6 => %17)::Int64
> │   %8  = Base.getfield(%1, %6, true)::Int64
> │         Base.arrayset(false, %2, %8, %5)::Vector{Int64}
> │   %10 = Base.add_int(%5, 1)::Int64
> │   %11 = (%7 === 2)::Bool
> └──       goto #4 if not %11
> 3 ─       goto #5
> 4 ─ %14 = Base.add_int(%7, 1)::Int64
> └──       goto #5
> 5 ┄ %16 = φ (#4 => %14)::Int64
> │   %17 = φ (#4 => %14)::Int64
> │   %18 = φ (#3 => true, #4 => false)::Bool
> │   %19 = Base.not_int(%18)::Bool
> └──       goto #7 if not %19
> 6 ─       goto #2
> 7 ┄       goto #8
> 8 ─ %23 = Core._expr(:(=), :X, %2)::Expr
> │   %24 = $(Expr(:copyast, :($(QuoteNode(:(for x = X
>       #= REPL[4]:6 =#
>       println(x)
>   end))))))::Expr
> │   %25 = Core._expr(:block, $(QuoteNode(:(#= REPL[4]:4 =#))), %23, $(QuoteNode(:(#= REPL[4]:5 =#))), %24)::Expr
> └──       return %25
> ) => Expr
> ```
> You can see statement `%24` took more than one line to print.

_Originally posted by @timholy in https://github.com/JuliaLang/julia/pull/37275#discussion_r480065548

### PR DESCRIPTION
**Pull request by kimikage**
This reduces misalignment by means of a heuristic.

Perhaps this is an imperfect measure, but I don't think misalignment in corner cases is a critical problem to be solved in this package.

Fixes #11

### CODE REVIEW

**Comment by timholy** [comment]
Yes, with the cost printer having been implemented in Base I don't think it's crucial to get this perfect. In case you want another stress-test, the lowered version of [this struct definition](https://github.com/timholy/Revise.jl/blob/a1a4020f84f5ef8c45678a6682d7fa1619d36c4c/test/sigtest.jl#L78-L87) is probably a serious challenge.

**Comment by kimikage** [comment]
> the lowered version of this struct definition is probably a serious challenge.

I don't really understand the specific challenge. What is essentially different from the example in #11?

**Comment by timholy** [comment]
May not be different, I just thought it was even harder given that the bracketing weaves together two separate CodeInfos.

**Comment by kimikage** [comment]
I don't know how to access the lowered version in the first place. :sob:

**Comment by timholy** [comment]
No worries, I should have explained: `Meta.lower(Main, ex)` should do the trick.

**Comment by timholy** [comment]
However, the optimizer may not produce much runtime code, so perhaps this isn't such a useful example after all. I just noticed it and thought, "man, that's a weird CodeInfo, I bet @kimakage would be pleased." :laughing:

**Pull request merged**
